en:
    blog.category.headline: 'Blog'
    blog.category.title: 'Blog category'
    blog.category.not_found: 'Category not found. Please continue to'
    blog.category.all_posts: 'list of all posts'
    blog.post.not_found: 'Post not found. Please continue to'
    blog.post.posted: 'Posted'
    blog.post.under: 'Under'
    blog.post.by: 'By'
    section.contact.headline: 'Contact Us'
    section.contact.map: 'Directions'
    section.contact.form: 'Email'
    section.contact.name: 'Name'
    section.contact.email: 'Email'
    section.contact.phone: 'Phone'
    section.contact.message: 'Message'
    section.contact.button: 'Send'
    section.cta.heading: 'WITH VEGA IMAGINATION IS YOUR ONLY LIMIT!'
    section.cta.button: 'Theme homepage'
    section.cta2.button: 'Upgrade to Pro'
    section.features.headline: 'Featured Pages'
    section.features.more: 'Learn More'
    section.intro.headline: 'ONE PAGE BUSINESS THEME'
    section.intro.button: 'View More'
    section.posts.headline: 'Latest Posts'
    section.posts.more: 'View more posts'
    section.welcome.headline: 'Welcome to Vega'
    section.welcome.button: 'Download Latest Version'
    sidebar.search.title: 'Search'
    sidebar.search.placeholder: 'Search...'
    sidebar.about.title: 'About Me'
    sidebar.recent.title: 'Recent Posts'
    sidebar.tags.title: 'Tags'
    footer.header.first: 'About Vega lite'
    footer.header.second: 'Categories'
    footer.header.third: 'Contact Us'
    footer.header.fourth: 'Follow Us'
    footer.facebook.like_us: 'Like Us'
cs:
    blog.category.headline: 'Články'
    blog.category.title: 'Kategorie článků'
    blog.category.not_found: 'Kategorie nenalezena. Prosím pokračujte na'
    blog.category.all_posts: 'seznam všech článků'
    blog.post.not_found: 'Článek nenalezen. Prosím pokračujte na'
    blog.post.posted: 'Zveřejněno'
    blog.post.under: 'V kategoriích'
    blog.post.by: 'Autor'
    section.contact.headline: 'Kontaktujte nás'
    section.contact.map: 'Jak se k nám dostanete'
    section.contact.form: 'E-mail'
    section.contact.name: 'Jméno a příjmení'
    section.contact.email: 'E-mailová adresa'
    section.contact.phone: 'Telefon'
    section.contact.message: 'Zpráva'
    section.contact.button: 'Odeslat'
    section.cta.heading: 'WITH VEGA IMAGINATION IS YOUR ONLY LIMIT!'
    section.cta.button: 'Domovská stránka'
    section.cta2.button: 'Upgrade to Pro'
    section.features.headline: 'Výhody'
    section.features.more: 'Více'
    section.intro.headline: 'ONE PAGE BUSINESS THEME'
    section.intro.button: 'View More'
    section.posts.headline: 'Blog'
    section.posts.more: 'Více článků'
    section.welcome.headline: 'Welcome to Vega'
    section.welcome.button: 'Stáhnout poslední verzi'
    sidebar.search.title: 'Vyhledávání'
    sidebar.search.placeholder: 'Hledat...'
    sidebar.about.title: 'O mně'
    sidebar.recent.title: 'Poslední články'
    sidebar.tags.title: 'Tagy'
    footer.header.first: 'O nás'
    footer.header.second: 'Kategorie blogu'
    footer.header.third: 'Kontaktujte nás'
    footer.header.fourth: 'Sledujte nás'
    footer.facebook.like_us: 'Lajkujte nás'
